spring:
  application:
    name: ms.ticket-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    show-sql: true